package pkg1;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

public class HelloTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\sagiz\\Downloads\\איכות תוכנה\\selenium\\chromedriver_win32\\chromedriver.exe");

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
//        driver.quit();
    }

    @Test
    public void hello() {
        // Test name: hello
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.saucedemo.com/");
        // 2 | setWindowSize | 1760x896 |
        driver.manage().window().setSize(new Dimension(1760, 896));

        String[] users = driver.findElement(By.id("login_credentials")).getText().split("\n");
        driver.findElement(By.id("user-name")).sendKeys(users[1]);
        driver.findElement(By.id("password")).sendKeys("secret_sauce");
        driver.findElement(By.id("login-button")).sendKeys(Keys.ENTER);

    }
}