// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

public class MacbookTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\sagiz\\Downloads\\איכות תוכנה\\selenium\\chromedriver_win32\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
//    driver.quit();
    }

    @Test
    public void macbook() {
        // Test name: macbook
        // Step # | name | target | value
        // 1 | open | /demo/index.php?route=common/home |
        driver.get("http://tutorialsninja.com/demo/index.php?route=common/home");
        // 2 | setWindowSize | 1760x898 |
        driver.manage().window().setSize(new Dimension(1760, 898));
        // 3 | click | name=search |
        driver.findElement(By.name("search")).click();
        // 4 | type | name=search | macbook air
        driver.findElement(By.name("search")).sendKeys("macbook air");
        // 5 | click | css=.btn-default |
        driver.findElement(By.cssSelector("#search > span > button")).click();
        driver.findElement(By.cssSelector("#content > div:nth-child(8) > div > div > div:nth-child(2) > div.button-group > button:nth-child(1) > span")).click();
        driver.findElement(By.cssSelector("#top-links > ul > li:nth-child(4) > a")).click();
        driver.findElement(By.cssSelector("#content > div.buttons.clearfix > div.pull-right > a")).click();

        WebElement myDynamicElement =
                (new WebDriverWait(driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.id("input-email")));
        // Insert some fake account details
        myDynamicElement.sendKeys("asa.b123@gmail.com");
        driver.findElement(By.id("input-password")).sendKeys("Aaq1w2e3r4t5");
        driver.findElement(By.id("button-login")).click();
        fillDetailsWithRandomInformationForCheckoutOrder();
    }

    private void fillDetailsWithRandomInformationForCheckoutOrder() {
        (new WebDriverWait(driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.id("input-payment-firstname"))).sendKeys("Asa");
        driver.findElement(By.id("input-payment-lastname")).sendKeys("Basa");
        driver.findElement(By.id("input-payment-address-1")).sendKeys("Something classified");
        driver.findElement(By.id("input-payment-city")).sendKeys("Brazil");
        driver.findElement(By.id("input-payment-postcode")).sendKeys("1010220");

        new Select(driver.findElement(By.id("input-payment-country"))).selectByVisibleText("Israel");
//        new WebDriverWait(driver, 10).until(ExpectedConditions.);
        new Select(driver.findElement(By.id("input-payment-zone"))).selectByVisibleText("Tel Aviv");

    }
}